 'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import {Plus,Minus,Menu,X,ArrowUpRight,ChevronLeft,ChevronRight,Check} from 'lucide-react';
import {cinematicMotion} from './lib/cinematic-motion';
import type LenisType from 'lenis';
const technologies=[
 {name:'The hydration ritual',sub:'01 / RESTORE & REPLENISH',headline:<>A moment.<br/><em>For your skin.</em></>,copy:'A considered facial experience, built around how your skin feels today. Your consultation shapes the care, products and pace.',image:'/images/mask-use.webp',focus:'RESTORE',tags:['Comfort','Hydration','Barrier care']},
 {name:'The skin renewal plan',sub:'02 / REFINE & RENEW',headline:<>Less guesswork.<br/><em>More intention.</em></>,copy:'Explore texture, tone and skin quality with a professional. Options, preparation and aftercare are explained before you choose your next step.',image:'/images/gel-texture.webp',focus:'RENEW',tags:['Texture','Tone','Personal care']}
];
const services=[
 ['Skin health','Understand your skin.','Breakouts, sensitivity, pigmentation or a change you want to understand. Start with a conversation, not a shopping list.','skin'],
 ['Aesthetic care','Feel more like yourself.','A thoughtful approach to skin quality and aesthetic treatments. A clear explanation of the options, with space to decide.','care'],
 ['Scalp & hair','Look beneath the surface.','Discuss scalp comfort, shedding and changes in hair density. An assessment comes before a treatment plan.','hair']
];
const questions=[{q:'What brings you here?',opts:['Breakouts or sensitivity','Tone or pigmentation','Texture and skin quality','Scalp and hair concerns']},{q:'How does your skin feel?',opts:['Dry or tight','Oily or congested','Sensitive or reactive','I am not sure']},{q:'What matters most to you?',opts:['Understanding the cause','A simple care routine','Exploring treatment options','Preparing for an occasion']},{q:'Where would you like to begin?',opts:['A first consultation','A treatment conversation','A review of my routine']}];
export default function Home(){
 const root=useRef<HTMLDivElement>(null);const [loading,setLoading]=useState(true);const [menu,setMenu]=useState(false);const [light,setLight]=useState(true);const [chapter,setChapter]=useState(0);const [layer,setLayer]=useState(0);const [active,setActive]=useState(0);const [quiz,setQuiz]=useState(false);const [step,setStep]=useState(0);const [answers,setAnswers]=useState<string[]>([]);const [faq,setFaq]=useState<number|null>(0);const [brief,setBrief]=useState('');const [saved,setSaved]=useState(false);const [enquirySummary,setEnquirySummary]=useState('');const [copied,setCopied]=useState(false);const pointer=useRef<{x:number,y:number}|null>(null);const dragged=useRef(false);
 useEffect(()=>{let alive=true;let done:ReturnType<typeof setTimeout>;const started=performance.now();const hero=document.querySelector<HTMLImageElement>('.hero img');const ready=()=>{done=setTimeout(()=>{if(alive)setLoading(false)},Math.max(0,1300-(performance.now()-started)))};if(hero?.complete)ready();else{hero?.addEventListener('load',ready,{once:true});hero?.addEventListener('error',ready,{once:true})}const cap=setTimeout(()=>setLoading(false),2000);return()=>{alive=false;clearTimeout(cap);clearTimeout(done);hero?.removeEventListener('load',ready);hero?.removeEventListener('error',ready)}},[]);
 useEffect(()=>{if(loading)return;let cancelled=false;let dispose=()=>{};void(async()=>{const [{gsap},{ScrollTrigger},{default:Lenis}]=await Promise.all([import('gsap'),import('gsap/ScrollTrigger'),import('lenis')]);if(cancelled)return;gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const lenis:LenisType=new Lenis({duration:1.05,anchors:true,prevent:node=>!!node.closest('.modal-backdrop,.mobile-menu')});const tick=(t:number)=>lenis.raf(t*1000);lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(tick);let release=()=>{};const ctx=gsap.context(()=>{
 if(root.current)release=cinematicMotion(gsap,ScrollTrigger,root.current);
 gsap.to('.hero-visual',{yPercent:12,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});
 gsap.to('.hero-stay',{xPercent:-9,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});
 gsap.fromTo('.manifesto-word',{color:'#85817a'},{color:'#18243b',stagger:.15,ease:'none',scrollTrigger:{trigger:'.manifesto',start:'top 70%',end:'bottom 65%',scrub:1}});
 const diagnosis=gsap.timeline({scrollTrigger:{trigger:'.changes',start:'top top',end:'+=85%',pin:true,scrub:1,onUpdate:s=>setChapter(Math.min(2,Math.floor(s.progress*3)))}});diagnosis.to('.aged-portrait',{clipPath:'circle(80% at 50% 48%)'},0).to('.time-portrait',{scale:1.1},0).to('.time-meter i',{scaleX:1},0);
 let scrollLayer=-1,scrollTech=-1;ScrollTrigger.create({trigger:'.science',start:'top top',end:'+=80%',pin:true,onUpdate:s=>{const n=Math.min(2,Math.floor(s.progress*3));if(n!==scrollLayer){scrollLayer=n;setLayer(n)}}});
 ScrollTrigger.create({trigger:'.treatment',start:'top top',end:'+=85%',pin:true,onUpdate:s=>{const n=Math.min(1,Math.floor(s.progress*2));if(n!==scrollTech){scrollTech=n;setActive(n)}}});
 gsap.fromTo('.foot-word',{yPercent:20},{yPercent:-5,ease:'none',scrollTrigger:{trigger:'.cta',start:'top bottom',end:'bottom bottom',scrub:1}});
 },root);return()=>{release();ctx.revert();gsap.ticker.remove(tick);lenis.destroy()}});dispose=()=>mm.revert()})();return()=>{cancelled=true;dispose()}},[loading]);
 useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setLight(['hero','changes','skin-portal','results','cta'].some(c=>e.target.classList.contains(c)))}),{rootMargin:'-1px 0px -94% 0px'});document.querySelectorAll('main section').forEach(e=>o.observe(e));return()=>o.disconnect()},[]);
 useEffect(()=>{if(!quiz&&!menu)return;const prev=document.activeElement as HTMLElement;const panel=document.querySelector<HTMLElement>(quiz?'.quiz-dialog':'.mobile-menu');panel?.focus();const old=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setQuiz(false);setMenu(false)}if(e.key==='Tab'){const els=panel?.querySelectorAll<HTMLElement>('button,a,input');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);prev?.focus()}},[quiz,menu]);

 const start=()=>{setMenu(false);setStep(0);setAnswers([]);setQuiz(true)};const t=technologies[active];
 const useBrief=()=>{setBrief(answers.join(' · '));setQuiz(false);setSaved(false);setTimeout(()=>document.getElementById('consultation')?.scrollIntoView({behavior:'smooth'}),100)};
 return <div ref={root}>
 {loading&&<div className="loader" aria-label="Preparing your experience"><span className="loader-mark">VELA<span>.</span></span><div className="loader-rule"><i/></div><p>COME BACK TO YOURSELF.</p></div>}
 <header className={menu?'menu-open':light?'nav-light':'nav-dark'}><a className="logo" href="#home" aria-label="VELA home">VELA</a><nav aria-label="Main navigation"><a href="#story">Our approach</a><a href="#directions">Skin & care</a><a href="#doctors">Your experience</a></nav><div className="nav-right"><button className="nav-consult" onClick={start}>Let’s begin <Plus size={14}/></button><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label={menu?'Close menu':'Open menu'}>{menu?<X/>:<Menu/>}</button></div></header>
 {menu&&<nav className="mobile-menu" aria-label="Mobile navigation" tabIndex={-1}>{[['Our approach','#story'],['Skin & care','#directions'],['Treatment rituals','#ritual'],['Your experience','#doctors'],['Plan a visit','#consultation']].map(([label,href],i)=><a href={href} key={href} onClick={()=>setMenu(false)}><span>0{i+1}</span>{label}<ArrowUpRight/></a>)}</nav>}
 <div className="journey-progress" aria-hidden="true"/>
 <main>
 <section className="hero" id="home"><div className="hero-visual"><Image src="/images/skin.webp" fill priority sizes="100vw" alt="An intimate portrait of natural skin in soft light"/></div><div className="hero-vignette"/><div className="hero-glint" aria-hidden="true"/><p className="hero-intro eyebrow">VELA / SKIN & AESTHETICS<br/>CONSIDERED CARE. NATURALLY YOU.</p><h1 className="hero-type"><span className="hero-stay">Still you.</span><em className="hero-you">Only closer.</em></h1><div className="hero-lower"><p>Your skin has a story.<br/>Let’s listen to it.</p><button className="hero-quiz" onClick={start}><span>Find your starting point</span><i><Plus size={25}/></i></button></div><div className="hero-clinic-label"><span>SKIN · CONFIDENCE · CARE</span><i/></div><div className="hero-bottom"><a href="#story">THE STORY OF YOUR SKIN <span className="scroll-line"/></a><span>A MORE PERSONAL APPROACH</span></div></section>
 <section className="manifesto section" id="story"><div className="section-kicker"><p className="eyebrow">01 / YOU, BEFORE ANYTHING</p><span>NOT AN IDEAL. AN INDIVIDUAL.</span></div><h2 className="manifesto-text">{'Good skin care begins with understanding.'.split(' ').map((w,i)=><span className="manifesto-word" key={i}>{w} </span>)}<em className="manifesto-word">You.</em></h2><div className="manifesto-bottom"><span className="vertical-rule"/><p>A little less pressure.<br/>A little more perspective.</p><p>A space for skin health and aesthetic care, where your questions shape the conversation and your comfort sets the pace.</p><a className="round-link" href="#directions" aria-label="Explore skin and care"><Plus/></a></div></section>
 <section className="changes" aria-label="From a question to a plan"><div className="time-portrait"><Image src="/images/beneath.webp" fill sizes="100vw" alt="An editorial close-up of skin texture"/><div className="aged-portrait"><div className="diagnostic-grid"/><span className="diagnostic-point point-one"/><span className="diagnostic-point point-two"/></div></div><div className="time-shade"/><div className="time-scan" aria-hidden="true"/><div className="time-top"><p className="eyebrow">02 / LOOK A LITTLE CLOSER</p><span>DETAILS MAKE THE DIFFERENCE.</span></div><div className="time-copy"><h2>{['Every detail','Every question','Every next step'][chapter]}<br/><em>{['has a story.','deserves time.','is personal.'][chapter]}</em></h2><p>{['What you notice. How it feels. What has changed.','Your routine, your history and what you hope for.','A considered plan, made with you.'][chapter]}</p></div><div className="time-bottom"><div className="time-chapters">{['Listen','Understand','Plan'].map((v,i)=><span className={chapter===i?'active':''} key={v}>0{i+1} / {v}</span>)}<div className="time-meter"><i/></div></div><p className="small">An artistic skin study.<br/>Not a diagnostic scan.</p></div></section>
 <section className="science section" id="science"><div className="section-kicker"><p className="eyebrow">03 / MORE THAN SKIN DEEP</p><span>UNDERSTANDING COMES FIRST.</span></div><div className="science-grid"><div className="science-art"><h2>A little<br/><em>deeper.</em></h2><div className="skin-diagram" aria-label="Illustration of three skin layers">{['surface','epidermis','dermis'].map((c,i)=><div className={'skin-layer '+c+(layer===i?' selected':'')} key={c}><span>0{i+1}</span></div>)}</div><p className="diagram-caption">THE LAYERS OF SKIN / A SIMPLIFIED VIEW</p></div><div className="layer-detail"><div className="layer-tabs" role="group" aria-label="Skin layers">{['Surface','Epidermis','Dermis'].map((s,i)=><button onClick={()=>setLayer(i)} aria-pressed={layer===i} className={layer===i?'active':''} key={s}><span>0{i+1}</span>{s}</button>)}</div><div className="layer-copy" key={layer}><p className="eyebrow">GET TO KNOW YOUR SKIN</p><h3>{['Your everyday barrier.','A constantly renewing layer.','Structure beneath the surface.'][layer]}</h3><p>{['The outermost skin surface helps retain moisture and protect against the environment. How it feels can be a useful place to begin a care conversation.','The epidermis is the outer layer of skin. Visible changes, tone and texture are considered alongside your routine and skin history.','The dermis contains connective tissue, blood vessels and other structures. Treatment choices need a professional assessment of suitability.'][layer]}</p><div className="ingredient"><span>START WITH A CONVERSATION</span><strong>{['Comfort. Moisture. Balance.','Tone. Texture. Renewal.','Skin quality. Individual needs.'][layer]}</strong></div></div><p className="small">A little skin education.<br/>Your consultation makes it personal.</p></div></div></section>
 <section className="skin-portal" aria-label="A personal approach to care"><div className="skin-portal-media portal-art" aria-hidden="true"/><div className="portal-dark"/><div className="portal-halo" aria-hidden="true"><i/><i/></div><p className="portal-still" aria-hidden="true">VELA.</p><div className="portal-product clinic-emblem" aria-hidden="true"><span>V</span></div><div className="portal-copy"><p className="eyebrow">SCIENCE / SENSITIVITY / YOU</p><h2>Care, with intention.<br/><em>Confidence, on your terms.</em></h2><p>Thoughtful choices. Clear explanations.<br/>Room to feel like yourself.</p></div></section>
 <section className="ingredient-journey" id="directions" aria-label="Explore care pathways">{services.map(([name,title,copy,slug],i)=><article className="ingredient-scene" key={slug}><span className="ingredient-count">0{i+1} / VELA</span><span className="ingredient-ghost" aria-hidden="true" data-word={['SKIN','CARE','HAIR'][i]}/><div className="ingredient-scene-copy"><p className="eyebrow">{name.toUpperCase()}</p><h2>{['Skin.','Care.','Hair.'][i]}</h2><strong>{title}</strong><p>{copy}</p><button onClick={start} className="text-link">Explore your options <ArrowUpRight size={18}/></button></div><div className="ingredient-orb" aria-hidden="true"><i/><i/><i/></div></article>)}</section>
 <section className="treatment section" id="ritual"><div className="section-kicker"><p className="eyebrow">04 / THE CARE RITUALS</p><span>A MOMENT TO RECONNECT.</span></div><div className="orbit-layout"><div className="orbit-stage" data-active={active} onDragStart={e=>e.preventDefault()} onPointerDown={e=>{dragged.current=false;pointer.current={x:e.clientX,y:e.clientY}}} onPointerUp={e=>{if(pointer.current&&Math.abs(e.clientX-pointer.current.x)>45&&Math.abs(e.clientY-pointer.current.y)<60){setActive(a=>1-a);dragged.current=true}pointer.current=null}} onPointerCancel={()=>{pointer.current=null;dragged.current=false}} onClickCapture={e=>{if(dragged.current){e.preventDefault();e.stopPropagation();dragged.current=false}}}><span className="orbit-word" aria-hidden="true">{t.focus}</span><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/>{technologies.map((tech,i)=><button className={'vessel vessel-'+i+(active===i?' selected':'')} onClick={()=>setActive(i)} aria-pressed={active===i} aria-label={`Explore ${tech.name}`} key={tech.name}><Image src={tech.image} fill draggable={false} sizes="(max-width:760px) 65vw, 35vw" alt={i===0?'An illustrative hydrogel facial ritual':'A macro study of clear hydrating gel'}/><span className="vessel-ingredients">{tech.tags.join(' · ')}</span></button>)}<span className="orbit-caption">SWIPE TO EXPLORE / TWO APPROACHES</span></div><div className="treatment-copy"><p className="eyebrow">{t.sub}</p><div className="product-copy" key={active}><h2>{t.headline}</h2><h3>{t.name}</h3><p>{t.copy}</p><details className="ingredient-details"><summary>Before you choose <Plus size={18}/></summary><p>A consultation is the first step. Suitability, potential side effects, preparation and aftercare should be discussed before any treatment.</p></details></div><div className="product-controls"><button onClick={()=>setActive(a=>1-a)} aria-label="Previous ritual"><ChevronLeft/></button><span>0{active+1}<i> / 02</i></span><button onClick={()=>setActive(a=>1-a)} aria-label="Next ritual"><ChevronRight/></button></div><button className="text-link" onClick={start}>Find your starting point <Plus size={18}/></button></div></div><p className="collection-footnote">PERSONAL CARE STARTS WITH A PROFESSIONAL ASSESSMENT. ILLUSTRATIVE TREATMENT IMAGERY.</p></section>
 <section className="results section" id="doctors"><div className="results-heading"><p className="eyebrow">05 / HOW CARE SHOULD FEEL</p><h2>Seen.<br/><em>Not rushed.</em></h2><p>A good consultation leaves you<br/>with clarity, not pressure.</p></div><div className="care-ledger">{[['A conversation, first.','Time for your concerns, your routine and the changes you have noticed.'],['Your options, explained.','A clear discussion of suitability, preparation, potential risks and aftercare.'],['A plan you understand.','What happens next, what to expect and what you can ask along the way.']].map(([title,copy],i)=><div className="care-row" key={title}><span className="eyebrow">0{i+1}</span><h3>{title}</h3><p>{copy}</p></div>)}</div><button className="text-link" onClick={start}>Make your first step <ArrowUpRight size={18}/></button></section>
 <section className="quiz-section section"><p className="eyebrow">A STARTING POINT / IN FOUR QUESTIONS</p><h2>Less scrolling for answers.<br/><em>More understanding you.</em></h2><button className="pill dark" onClick={start}>Build my consultation brief <Plus size={16}/></button><p className="small">About a minute. No diagnosis. Just a clearer conversation.</p></section>
 <section className="faq section"><p className="eyebrow">A FEW THINGS YOU MAY BE WONDERING</p>{[['I am not sure what I need. Where do I start?','Start with a consultation. Bring your questions, your current routine and a sense of what has changed. You do not need to choose a procedure before you arrive.'],['Can I have a treatment at my first visit?','That depends on the treatment and your individual suitability. A professional should discuss your skin history, assess any contraindications and explain preparation before proceeding.'],['What should I bring to a consultation?','A list of your current skin products, relevant medications and previous treatments can help. Write down your concerns and questions so you leave with the answers that matter to you.'],['Will the skin finder recommend a treatment?','It creates a conversation brief from your answers. It does not diagnose a condition or decide whether a treatment is suitable. Those decisions belong in a professional consultation.']].map(([q,a],i)=><div className="faq-item" key={q}><button aria-expanded={faq===i} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus/>:<Plus/>}</button>{faq===i&&<p>{a}</p>}</div>)}</section>
 <section className="cta section" id="consultation"><span className="foot-word" aria-hidden="true"/><p className="eyebrow">06 / YOUR NEXT CHAPTER</p><h2>A little time.<br/><em>Just for you.</em></h2><div className="clinic-layout"><div className="clinic-image"><Image src="/images/studio.webp" fill sizes="(max-width:760px) 100vw, 45vw" alt="An illustrative VELA consultation space in warm stone and soft daylight"/><span>VELA / A SPACE TO FEEL AT EASE</span></div><div className="branch-panel"><p className="eyebrow">BEGIN WITH A CONVERSATION</p><p className="enquiry-intro">Tell us what you would like to explore.<br/>A considered first step starts here.</p><form className="enquiry-form" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);setEnquirySummary(`${data.get('name')} · ${data.get('interest')} · ${data.get('message')||'A first consultation'}`);setSaved(true)}}><div className="enquiry-fields"><label>Your name<input name="name" autoComplete="given-name" placeholder="First name" required maxLength={80}/></label><label>What brings you here?<select name="interest" defaultValue="Skin health"><option>Skin health</option><option>Aesthetic care</option><option>Scalp & hair</option><option>I am not sure yet</option></select></label></div><label>Your questions<textarea name="message" value={brief} onChange={e=>{setBrief(e.target.value);setSaved(false)}} placeholder="A concern, a goal, or simply where to begin…" maxLength={1200} rows={3}/></label><button className="pill light" type="submit">Prepare my enquiry <ArrowUpRight size={17}/></button><p className="form-note">Concept preview: prepare a brief here. No appointment is booked and no details are sent.</p></form>{saved&&<div className="enquiry-confirmation" role="status"><Check size={18}/><div><strong>Your brief is ready.</strong><p>{enquirySummary}</p><button className="text-link" onClick={async()=>{try{await navigator.clipboard.writeText(enquirySummary);setCopied(true)}catch{setCopied(false)}}}>{copied?'Copied to clipboard':'Copy my brief'} <ArrowUpRight size={15}/></button></div></div>}</div></div></section>
 </main><footer><a className="logo" href="#home">VELA</a><p>Come back to yourself.</p><span>A skin & aesthetics concept by Copywrk.<br/>Illustrative imagery. An original portfolio experience.</span><a href="https://copywrk.website" target="_blank" rel="noreferrer">Made by Copywrk <ArrowUpRight size={14}/></a></footer>
 {quiz&&<div className="modal-backdrop" onClick={e=>{if(e.currentTarget===e.target)setQuiz(false)}}><div className="quiz-dialog" role="dialog" aria-modal="true" aria-labelledby="quiz-title" tabIndex={-1}><button className="quiz-close" aria-label="Close questions" onClick={()=>setQuiz(false)}><X/></button><span className="logo">VELA</span>{step<4?<><p className="eyebrow">YOUR SKIN / 0{step+1} OF 04</p><div className="quiz-progress"><i style={{width:`${(step+1)*25}%`}}/></div><h2 id="quiz-title">{questions[step].q}</h2><div className="answers">{questions[step].opts.map(a=><button key={a} onClick={()=>{setAnswers([...answers.slice(0,step),a]);setStep(step+1)}}>{a}<Plus size={15}/></button>)}</div>{step>0&&<button className="quiz-back" onClick={()=>setStep(step-1)}>Back</button>}</>:<><p className="eyebrow">YOUR CONVERSATION STARTER</p><h2 id="quiz-title">Let’s start<br/><em>with you.</em></h2><ul>{answers.map(a=><li key={a}><Check size={16}/>{a}</li>)}</ul><p>{answers[0]==='Scalp and hair concerns'?'Begin with a scalp and hair consultation.':'Begin with a skin consultation.'} Bring your routine and questions. A professional assessment can help you understand the next step.</p><button className="pill dark" onClick={useBrief}>Use my consultation brief <ArrowUpRight size={16}/></button><p className="small">This is a conversation brief, not a diagnosis or treatment recommendation. Your answers stay on this page.</p><button className="quiz-back" onClick={start}>Start again</button></>}</div></div>}
 </div>
}
