'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import type LenisType from 'lenis';
import {cinematicMotion} from './lib/cinematic-motion';
import {Plus,Minus,Menu,X,MoveHorizontal,Check,MessageCircle,ChevronLeft,ChevronRight} from 'lucide-react';
const products=[
 {name:'Hydration booster',sub:'01 / THE DAILY RESET',copy:'Lightweight care. A thoughtful starting point for skin that feels thirsty, tight or out of balance.',ingredients:['Hyaluronic acid','Glycerin','Niacinamide'],image:'/images/booster.webp',ritual:'A little. Then a little more.',focus:'HYDRATE'},
 {name:'Hydrogel mask',sub:'02 / THE SLOW MOMENT',copy:'Take a breath. A cooling, close-fitting mask ritual centred on hydration and skin comfort.',ingredients:['Hyaluronic acid','Panthenol','Glycerin'],image:'/images/mask.webp',ritual:'A moment that is only yours.',focus:'SOAK'}
];
const questions=[{q:'What brings you here?',opts:['Dehydration & tightness','Uneven-looking tone','Fine lines','A routine that feels right']},{q:'How does your skin usually feel?',opts:['Dry','Oily','Combination','Sensitive']},{q:'How does your skin react to new products?',opts:['Usually comfortable','Sometimes irritated','Often irritated','I’m not sure']},{q:'What feels manageable?',opts:['A simple daily ritual','A salon consultation','Both, with guidance','Help me decide']}];
const reflections=[{title:'Good skin days begin with listening.',copy:'Tell your professional about your routine, sensitivities and what you would like to change.'},{title:'Consistency over intensity.',copy:'A comfortable routine you can keep is a better starting point than doing everything at once.'},{title:'Your progress is personal.',copy:'Discuss realistic expectations and how your skin responds. Results vary from person to person.'}];
const phone=process.env.NEXT_PUBLIC_WHATSAPP_NUMBER?.replace(/\D/g,'');
export default function Home(){
const root=useRef<HTMLDivElement>(null);const [menu,setMenu]=useState(false);const [loading,setLoading]=useState(true);const [active,setActive]=useState(0);const [layer,setLayer]=useState(0);const [slider,setSlider]=useState(50);const [quiz,setQuiz]=useState(false);const [step,setStep]=useState(0);const [answers,setAnswers]=useState<string[]>([]);const [review,setReview]=useState(0);const [openFaq,setOpenFaq]=useState<number|null>(0);const [city,setCity]=useState('');const [searched,setSearched]=useState(false);const [skinChapter,setSkinChapter]=useState(0);const [heroAge,setHeroAge]=useState(21);const [navLight,setNavLight]=useState(true);const dragStart=useRef<{x:number,y:number}|null>(null);const dragged=useRef(false);
const wa=phone?`https://wa.me/${phone.length===10?'91'+phone:phone}?text=${encodeURIComponent('Hello, I would like to discuss a skin consultation.')}`:undefined;
useEffect(()=>{let disposed=false;const started=performance.now();const assets=[...document.querySelectorAll<HTMLImageElement>('.hero img')];Promise.all(assets.map(img=>img.complete?Promise.resolve():new Promise<void>(resolve=>{img.addEventListener('load',()=>resolve(),{once:true});img.addEventListener('error',()=>resolve(),{once:true})}))).then(()=>{const wait=Math.max(0,1500-(performance.now()-started));window.setTimeout(()=>{if(!disposed)setLoading(false)},wait)});const timeout=window.setTimeout(()=>setLoading(false),2000);return()=>{disposed=true;clearTimeout(timeout)}},[]);
useEffect(()=>{if(loading)return;let cancelled=false;let dispose=()=>{};const initialize=async()=>{const [{gsap},{ScrollTrigger},{default:Lenis}]=await Promise.all([import('gsap'),import('gsap/ScrollTrigger'),import('lenis')]);if(cancelled)return;gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();let lenis:LenisType|undefined;let tick:((time:number)=>void)|undefined;
mm.add('(prefers-reduced-motion: no-preference)',()=>{lenis=new Lenis({duration:1.1,anchors:true,prevent:node=>!!node.closest('.modal-backdrop,.mobile-menu')});lenis.on('scroll',ScrollTrigger.update);tick=(time)=>lenis?.raf(time*1000);gsap.ticker.add(tick);gsap.ticker.lagSmoothing(0);
let disposeMotion=()=>{};
const ctx=gsap.context(()=>{
 if(root.current)disposeMotion=cinematicMotion(gsap,ScrollTrigger,root.current);

 gsap.to('.hero-visual',{yPercent:12,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});
 gsap.to('.hero-stay',{xPercent:-14,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});
 ScrollTrigger.create({trigger:'.hero',start:'top top',end:'bottom top',onUpdate:self=>{const ages=[21,25,30,35,40];setHeroAge(ages[Math.min(4,Math.floor(self.progress*5))])}});
 gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.fromTo(el,{y:30,opacity:0},{y:0,opacity:1,duration:.8,scrollTrigger:{trigger:el,start:'top 92%'}}));
 gsap.fromTo('.manifesto-word',{color:'#868075'},{color:'#171715',stagger:.15,ease:'none',scrollTrigger:{trigger:'.manifesto',start:'top 70%',end:'bottom 65%',scrub:1}});
 const age=gsap.timeline({scrollTrigger:{trigger:'.changes',start:'top top',end:'+=100%',pin:true,scrub:1,onUpdate:self=>setSkinChapter(Math.min(2,Math.floor(self.progress*3)))}});
 age.to('.aged-portrait',{clipPath:'circle(80% at 50% 48%)'},0).to('.time-portrait',{scale:1.08},0).to('.time-meter i',{scaleX:1},0);
 let scrollLayer=-1,scrollProduct=-1;
 ScrollTrigger.create({trigger:'.science',start:'top top',end:'+=100%',pin:true,scrub:1,onUpdate:self=>{const next=Math.min(2,Math.floor(self.progress*3));if(next!==scrollLayer){scrollLayer=next;setLayer(next)}}});
 ScrollTrigger.create({trigger:'.treatment',start:'top top',end:'+=100%',pin:true,scrub:1,onUpdate:self=>{const next=Math.min(1,Math.floor(self.progress*2));if(next!==scrollProduct){scrollProduct=next;setActive(next)}}});
 gsap.fromTo('.foot-word',{yPercent:20},{yPercent:-5,ease:'none',scrollTrigger:{trigger:'.cta',start:'top bottom',end:'bottom bottom',scrub:1}});
},root);return()=>{disposeMotion();ctx.revert();if(tick)gsap.ticker.remove(tick);lenis?.destroy()}});
dispose=()=>mm.revert()};void initialize();return()=>{cancelled=true;dispose()}},[loading]);
useEffect(()=>{const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)setNavLight(['hero','changes','skin-portal','results','cta'].some(c=>entry.target.classList.contains(c)))})},{rootMargin:'-1px 0px -94% 0px',threshold:0});document.querySelectorAll('main section').forEach(section=>observer.observe(section));return()=>observer.disconnect()},[]);
useEffect(()=>{if(!quiz)return;const prev=document.activeElement as HTMLElement;const dialog=document.querySelector<HTMLElement>('.quiz-dialog');dialog?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setQuiz(false);if(e.key==='Tab'){const nodes=dialog?.querySelectorAll<HTMLElement>('button,a,input');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=old;prev?.focus()}},[quiz]);
function startQuiz(){setStep(0);setAnswers([]);setQuiz(true)}
const result=answers[2]==='Often irritated'||answers[1]==='Sensitive'?'Comfort first':answers[0]==='Uneven-looking tone'?'A thoughtful tone routine':answers[0]==='Fine lines'?'Hydration, with consistency':'Your hydration starting point';
return <div ref={root}>
{loading&&<div className="loader" aria-label="Preparing your skin journey"><span className="loader-mark">STILL<span>.</span></span><div className="loader-rule"><i/></div><p>TAKE A MOMENT.</p></div>}
<header className={menu?'menu-open':navLight?'nav-light':'nav-dark'}><a href="#" className="logo" aria-label="STILL· home">STILL<span>·</span></a><nav aria-label="Main navigation"><a href="#story">Our point of view</a><a href="#science">Beneath the surface</a><a href="#ritual">The collection</a></nav><div className="nav-right"><button className="nav-consult" onClick={startQuiz}>Find your ritual <Plus size={14}/></button><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></header>
{menu&&<nav className="mobile-menu" aria-label="Mobile navigation">{[['Our point of view','#story'],['Beneath the surface','#science'],['The collection','#ritual'],['Find your ritual','#consultation']].map(([label,href],i)=><a key={href} href={href} onClick={()=>setMenu(false)}><span>0{i+1}</span>{label}<Plus size={25}/></a>)}</nav>}
<div className="journey-progress" aria-hidden="true"/>
<main>
<section className="hero" id="home">
 <div className="hero-visual"><Image src="/images/campaign.webp" alt="A chrome STILL bottle suspended in a sculptural ribbon of clear gel" fill priority sizes="100vw"/></div>
 <div className="hero-vignette"/><div className="hero-glint" aria-hidden="true"/>
 <p className="hero-intro eyebrow">PROFESSIONAL SKINCARE.<br/>DEEPLY PERSONAL.</p>
 <h1 className="hero-type"><span className="hero-stay">STAY</span><em className="hero-you">you.</em></h1>
 <div className="hero-lower"><p>Time moves.<br/>You set the terms.</p><button className="hero-quiz" onClick={startQuiz}><span>Discover your skin ritual</span><i><Plus size={25}/></i></button></div>
 <div className="age-rail" aria-label={`Skin timeline, age ${heroAge}`}><strong>{heroAge}</strong><div>{[21,25,30,35,40].map(age=><span key={age} className={heroAge===age?'active':''}>{age}<i/></span>)}</div></div>
 <div className="hero-bottom"><a href="#story">SCROLL TO MOVE THROUGH TIME <span className="scroll-line"/></a><span>STILL / EST. NOW</span></div>
</section>
<section className="manifesto section" id="story">
 <div className="section-kicker"><p className="eyebrow">01 / A DIFFERENT POINT OF VIEW</p><span>SKIN IS PERSONAL.</span></div>
 <h2 className="manifesto-text" aria-label="Not younger. Not different. Just beautifully, unmistakably you.">{'Not younger. Not different. Just beautifully, unmistakably'.split(' ').map((word,i)=><span className="manifesto-word" key={i}>{word} </span>)}<em className="manifesto-word">you.</em></h2>
 <div className="manifesto-bottom"><span className="vertical-rule"/><p>Every late night. Every sunny afternoon.<br/>Every year of being you.</p><p>Skin changes. Our approach starts with understanding yours, then finding a ritual that belongs in your life.</p><a className="round-link" href="#science" aria-label="Explore beneath the surface"><Plus size={22}/></a></div>
</section>
<section className="changes" aria-label="The changing story of skin">
 <div className="time-portrait"><Image src="/images/skin.webp" fill sizes="100vw" alt="Natural skin portrait"/><div className="aged-portrait"><Image src="/images/skin-time.webp" fill sizes="100vw" alt="An illustrative older appearance of the same portrait"/></div></div><div className="time-shade"/><div className="time-scan" aria-hidden="true"/>
 <div className="time-top"><p className="eyebrow">02 / THE MARKS OF LIVING</p><span>YOUR SKIN HAS BEEN THERE.</span></div>
 <div className="time-copy"><h2>Life leaves<br/><em>a trace.</em></h2><p>{['A texture that changes.','A tone with its own story.','A need for a little more comfort.'][skinChapter]}</p></div>
 <div className="time-bottom"><div className="time-chapters">{['Texture','Tone','Comfort'].map((c,i)=><span key={c} className={skinChapter===i?'active':''}>0{i+1} / {c}</span>)}<div className="time-meter"><i/></div></div><p className="small">Illustrative ageing portrait.<br/>Not a treatment result or prediction.</p></div>
</section>
<section className="science section" id="science">
 <div className="section-kicker"><p className="eyebrow">03 / BENEATH THE SURFACE</p><span>CARE BEGINS WITH UNDERSTANDING.</span></div>
 <div className="science-grid"><div className="science-art"><h2>A little<br/><em>deeper.</em></h2><div className="skin-diagram" aria-label="Simplified skin cross-section"><div className={'skin-layer surface '+(layer===0?'selected':'')}><span>01</span></div><div className={'skin-layer epidermis '+(layer===1?'selected':'')}><span>02</span></div><div className={'skin-layer dermis '+(layer===2?'selected':'')}><span>03</span></div></div><p className="diagram-caption">SKIN CROSS-SECTION / SIMPLIFIED</p></div>
 <div className="layer-detail"><div className="layer-tabs" role="group" aria-label="Skin layers">{['Surface','Epidermis','Dermis'].map((l,i)=><button aria-pressed={layer===i} key={l} onClick={()=>setLayer(i)} className={layer===i?'active':''}><span>0{i+1}</span>{l}</button>)}</div><div className="layer-copy" key={layer}><p className="eyebrow">{['THE FIRST LINE','THE PROTECTIVE LAYER','THE SUPPORT STRUCTURE'][layer]}</p><h3>{['Comfort starts here.','Respect the barrier.','Know the foundations.'][layer]}</h3><p>{['The outer surface helps keep moisture in. Humectants such as glycerin and hyaluronic acid are used in skincare to support hydration.','The epidermis is your outer protective layer. Ceramides are used in moisturisers designed to support its moisture barrier.','The dermis contains connective tissue, blood vessels and other structures. A topical ritual is not a promise to rebuild this layer.'][layer]}</p><div className="ingredient"><span>{['HYDRATION FOCUS','BARRIER FOCUS','PROFESSIONAL GUIDANCE'][layer]}</span><strong>{['Glycerin + hyaluronic acid','Ceramides + gentle care','An individual consultation'][layer]}</strong></div></div><p className="small">Ingredient education, not a product penetration claim.<br/>Ask your professional about suitability.</p></div></div>
</section>
<section className="skin-portal" aria-label="From skin to formula">
 <div className="skin-portal-media"><Image src="/images/skin-time.webp" fill sizes="100vw" alt="Macro skin texture transitioning into the STILL formula"/></div>
 <div className="portal-dark"/><div className="portal-halo" aria-hidden="true"><i/><i/></div>
 <p className="portal-still">STILL.</p>
 <div className="portal-product"><Image src="/images/booster.webp" fill sizes="(max-width:760px) 65vw, 34vw" alt="STILL hydration booster"/></div>
 <div className="portal-copy"><p className="eyebrow">FROM TIME / TO RITUAL</p><h2>Time changes skin.<br/><em>Your ritual shapes the response.</em></h2><p>Less noise. More consistency. A formula becomes useful when it earns a place in your everyday life.</p></div>
 </section>
 <section className="ingredient-journey" aria-label="Inside the formula">
 {[['RETINAL','CELL TURNOVER','A considered active for routines focused on visible signs of time.'],['PEPTIDES','STRUCTURE','Supportive skincare ingredients, framed without miracle language.'],['CERAMIDES','BARRIER','Lipids used in moisturising care to support the skin barrier.']].map((item,i)=><article className="ingredient-scene" key={item[0]}><span className="ingredient-count">0{i+1}</span><span className="ingredient-ghost">{item[0]}</span><div className="ingredient-scene-copy"><p className="eyebrow">INSIDE THE FORMULA</p><h2>{item[0]}</h2><strong>{item[1]} <span>↑</span></strong><p>{item[2]}</p></div><div className="ingredient-orb"><i/><i/><i/></div></article>)}
 </section>
<section className="treatment section" id="ritual">
 <div className="section-kicker"><p className="eyebrow">04 / THE COLLECTION</p><span>LESS NOISE. MORE RITUAL.</span></div>
 <div className="orbit-layout"><div className="orbit-stage" data-active={active} onDragStart={e=>e.preventDefault()}
 onPointerDown={e=>{dragged.current=false;dragStart.current={x:e.clientX,y:e.clientY}}}
 onPointerUp={e=>{if(dragStart.current){const dx=e.clientX-dragStart.current.x,dy=e.clientY-dragStart.current.y;if(Math.abs(dx)>45&&Math.abs(dy)<60){setActive(active===0?1:0);dragged.current=true}dragStart.current=null}}}
 onPointerCancel={()=>{dragStart.current=null;dragged.current=false}} onClickCapture={e=>{if(dragged.current){e.preventDefault();e.stopPropagation();dragged.current=false}}}>
 <span className="orbit-word" aria-hidden="true">{products[active].focus}</span><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/>
 {products.map((p,i)=><button key={p.name} className={'vessel vessel-'+i+(active===i?' selected':'')} onClick={()=>setActive(i)} aria-label={`Select ${p.name}`} aria-pressed={active===i}><Image draggable={false} src={p.image} alt={p.name+' concept packaging'} fill sizes="(max-width:760px) 65vw, 35vw"/><span className="vessel-ingredients">{p.ingredients[0]}<br/>{p.ingredients[1]}</span></button>)}
 <span className="orbit-caption">DRAG TO DISCOVER / OR USE THE CONTROLS</span>
 </div>
 <div className="treatment-copy"><p className="eyebrow">{products[active].sub}</p><div className="product-copy" key={active}><h2>{active===0?<>A daily<br/><em>reset.</em></>:<>A slow<br/><em>moment.</em></>}</h2><h3>{products[active].name}</h3><p>{products[active].copy}</p><details className="ingredient-details"><summary>Inside the ritual <Plus size={18}/></summary><p>{products[active].ingredients.join(' · ')}</p><span className="small">Concept formulations. Final ingredients require verification.</span></details></div>
 <div className="product-controls"><button onClick={()=>setActive(active===0?1:0)} aria-label="Previous ritual"><ChevronLeft size={22}/></button><span>0{active+1} <i>/ 02</i></span><button onClick={()=>setActive(active===0?1:0)} aria-label="Next ritual"><ChevronRight size={22}/></button></div>
 <button className="text-link" onClick={startQuiz}>Find your ritual <Plus size={18}/></button></div>
 </div><p className="collection-footnote">CONCEPT COLLECTION / PROFESSIONAL GUIDANCE BEFORE USE</p>
</section>
<section className="results section" id="results"><div className="results-heading"><p className="eyebrow">05 / A CLOSER LOOK</p><h2>Look closer.<br/><em>Stay honest.</em></h2><p>Real progress deserves honest documentation.<br/>Same angle. Same lighting. No filters.</p></div><div className="comparison"><div className="compare-photo base"><Image src="/images/skin.webp" fill sizes="(max-width:760px) 100vw, 65vw" alt="Original illustrative skin portrait"/></div><div className="compare-photo overlay" style={{clipPath:`inset(0 ${100-slider}% 0 0)`}}><Image src="/images/skin.webp" fill sizes="(max-width:760px) 100vw, 65vw" alt="The same portrait with altered lighting for a slider demonstration"/></div><span className="compare-label left">ORIGINAL LIGHT</span><span className="compare-label right">ALTERED LIGHT</span><div className="slider-handle" style={{left:`${slider}%`}}><span><MoveHorizontal size={22}/></span></div><input type="range" min="0" max="100" value={slider} onChange={e=>setSlider(Number(e.target.value))} aria-label="Compare original and altered lighting"/></div><p className="comparison-note">Interactive lighting demonstration only — not before-and-after treatment evidence.</p><div className="reflections"><p className="eyebrow">CARE NOTES / {String(review+1).padStart(2,'0')}</p><h3>“{reflections[review].title}”</h3><p>{reflections[review].copy}</p><div className="dots">{reflections.map((r,i)=><button key={i} aria-label={`Care note ${i+1}`} aria-pressed={review===i} className={review===i?'active':''} onClick={()=>setReview(i)}/>)}</div><span className="small">Verified client reviews will take their place here.</span></div></section>
<section className="quiz-section section"><p className="eyebrow">FOUR QUESTIONS. A THOUGHTFUL START.</p><h2>Your skin.<br/><em>Your starting point.</em></h2><button className="pill dark" onClick={startQuiz}>Find your starting point <Plus size={16}/></button><p className="small">About a minute. No email required.</p></section>
<section className="faq section"><p className="eyebrow">A FEW THINGS, ANSWERED</p>{[['Is this a replacement for a dermatologist?','No. These rituals and the quiz are general skincare education. Persistent irritation, acne or changing skin lesions should be discussed with a dermatologist.'],['How do I choose a treatment?','Start with a consultation. Share your concerns, current routine, sensitivities and any recent treatments so your professional can assess suitability.'],['Will everyone see the same results?','No. Skin response varies. Discuss realistic expectations, the products used and aftercare with your professional.']].map(([q,a],i)=><div className="faq-item" key={q}><button aria-expanded={openFaq===i} onClick={()=>setOpenFaq(openFaq===i?null:i)}>{q}{openFaq===i?<Minus size={18}/>:<Plus size={18}/>}</button>{openFaq===i&&<p>{a}</p>}</div>)}</section>
<section className="cta section" id="consultation"><span className="foot-word" aria-hidden="true">STILL.</span><p className="eyebrow">06 / THE NEXT CHAPTER IS YOURS</p><h2>The next chapter.<br/><em>Yours.</em></h2><div className="cta-grid"><p>Good care starts with a conversation.<br/>Find professional guidance for your skin.</p><form onSubmit={e=>{e.preventDefault();setSearched(true)}}><label htmlFor="city">Find a salon near you</label><div className="city-field"><input id="city" value={city} onChange={e=>{setCity(e.target.value);setSearched(false)}} placeholder="Your city or postcode" required/><button type="submit" aria-label="Search salons"><Plus/></button></div>{searched&&<p className="search-message">The verified salon directory is coming soon. {wa?<a href={wa} target="_blank" rel="noreferrer">Ask the team about {city}.</a>:'Use your quiz summary to begin a conversation with a local skin professional.'}</p>}</form></div>{wa?<a className="text-link" href={wa} target="_blank" rel="noreferrer">WhatsApp a consultation enquiry <MessageCircle size={16}/></a>:<button className="text-link" onClick={startQuiz}>Prepare your consultation <Plus size={16}/></button>}</section>
</main><footer><a href="#" className="logo">STILL<span>·</span></a><p>Stay beautifully you.</p><span>© {new Date().getFullYear()} STILL · Independent brand concept by Copywrk.</span><a href="#home">Back to the beginning</a></footer>
{quiz&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setQuiz(false)}}><div className="quiz-dialog" role="dialog" aria-modal="true" aria-labelledby="quiz-title" tabIndex={-1}><button className="quiz-close" aria-label="Close quiz" onClick={()=>setQuiz(false)}><X/></button><span className="logo">STILL.</span>{step<4?<><p className="eyebrow">YOUR SKIN, UNDERSTOOD / 0{step+1} OF 04</p><div className="quiz-progress"><i style={{width:`${(step+1)*25}%`}}/></div><h2 id="quiz-title">{questions[step].q}</h2><div className="answers">{questions[step].opts.map(a=><button key={a} onClick={()=>{setAnswers([...answers.slice(0,step),a]);setStep(step+1)}}>{a}<Plus size={15}/></button>)}</div>{step>0&&<button className="quiz-back" onClick={()=>setStep(step-1)}>Previous question</button>}</>:<><p className="eyebrow">YOUR CONVERSATION STARTER</p><h2 id="quiz-title">{result}</h2><p>{result==='Comfort first'?'Start gently. Discuss your sensitivity with a professional before trying active ingredients or a salon treatment.':'Discuss a gentle hydration and barrier-support routine, daily sun protection and whether a salon ritual suits your skin.'}</p><ul>{answers.map((a,i)=><li key={i}><Check size={16}/>{a}</li>)}</ul><p className="small">A suggested discussion topic, not a diagnosis or personalised treatment prescription.</p><a className="pill dark" href={wa?`${wa.split('?')[0]}?text=${encodeURIComponent('Hello, I would like a skin consultation. My quiz summary: '+answers.join('; '))}`:'#consultation'} onClick={()=>setQuiz(false)}>Discuss your starting point <Plus size={16}/></a><button className="quiz-back" onClick={startQuiz}>Start again</button></>}</div></div>}
</div>}
