'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import type LenisType from 'lenis';
import {cinematicMotion} from './lib/cinematic-motion';
import {Plus,Minus,Menu,X,Check,MessageCircle,ChevronLeft,ChevronRight} from 'lucide-react';
const products=[
 {name:'Hydration booster',sub:'THE DAILY RESET',size:'30 ml · Sample specification',use:'Apply a small amount after cleansing, then follow with moisturiser. Daytime routines finish with sunscreen.',copy:'A lightweight hydration step for skin that feels dry or tight.',ingredients:['Hyaluronic acid','Glycerin'],image:'/images/booster.webp',ritual:'A little. Then a little more.',focus:'HYDRATE'},
 {name:'Hydrogel mask',sub:'THE SLOW MOMENT',size:'Single-use sheet · Sample specification',use:'An occasional hydration step after cleansing. For a real product, follow the wear time and instructions on its packaging.',copy:'A cooling sheet-mask concept for an occasional moment of hydration and comfort.',ingredients:['Hyaluronic acid','Panthenol','Glycerin'],image:'/images/mask.webp',ritual:'A moment that is only yours.',focus:'SOAK'}
];
const questions=[{q:'What brings you here?',opts:['Dehydration & tightness','Uneven-looking tone','Fine lines','A routine that feels right']},{q:'How does your skin usually feel?',opts:['Dry','Oily','Combination','Sensitive']},{q:'How does your skin react to new products?',opts:['Usually comfortable','Sometimes irritated','Often irritated','I’m not sure']},{q:'What feels manageable?',opts:['A simple daily ritual','A salon consultation','Both, with guidance','Help me decide']}];
const reflections=[{title:'Good skin days begin with listening.',copy:'Tell your professional about your routine, sensitivities and what you would like to change.'},{title:'Consistency over intensity.',copy:'A comfortable routine you can keep is a better starting point than doing everything at once.'},{title:'Your progress is personal.',copy:'Discuss realistic expectations and how your skin responds. Results vary from person to person.'}];
const phone=process.env.NEXT_PUBLIC_WHATSAPP_NUMBER?.replace(/\D/g,'');
export default function Home(){
const root=useRef<HTMLDivElement>(null);const [menu,setMenu]=useState(false);const [loading,setLoading]=useState(true);const [active,setActive]=useState(0);const [layer,setLayer]=useState(0);const [quiz,setQuiz]=useState(false);const [step,setStep]=useState(0);const [answers,setAnswers]=useState<string[]>([]);const [review,setReview]=useState(0);const [openFaq,setOpenFaq]=useState<number|null>(0);const [policy,setPolicy]=useState<'privacy'|'terms'|null>(null);const [saved,setSaved]=useState(false);const [navLight,setNavLight]=useState(true);const dragStart=useRef<{x:number,y:number}|null>(null);const dragged=useRef(false);
const wa=phone?`https://wa.me/${phone.length===10?'91'+phone:phone}?text=${encodeURIComponent('Hello, I would like to discuss a skin consultation.')}`:undefined;
useEffect(()=>{let disposed=false;const started=performance.now();const assets=[...document.querySelectorAll<HTMLImageElement>('.hero img')];Promise.all(assets.map(img=>img.complete?Promise.resolve():new Promise<void>(resolve=>{img.addEventListener('load',()=>resolve(),{once:true});img.addEventListener('error',()=>resolve(),{once:true})}))).then(()=>{const wait=Math.max(0,400-(performance.now()-started));window.setTimeout(()=>{if(!disposed)setLoading(false)},wait)});const timeout=window.setTimeout(()=>setLoading(false),2000);return()=>{disposed=true;clearTimeout(timeout)}},[]);
useEffect(()=>{if(loading)return;let cancelled=false;let dispose=()=>{};const initialize=async()=>{if(window.matchMedia('(max-width:760px), (prefers-reduced-motion:reduce)').matches)return;const [{gsap},{ScrollTrigger},{default:Lenis}]=await Promise.all([import('gsap'),import('gsap/ScrollTrigger'),import('lenis')]);if(cancelled)return;gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();let lenis:LenisType|undefined;let tick:((time:number)=>void)|undefined;
mm.add('(prefers-reduced-motion: no-preference) and (min-width: 761px)',()=>{lenis=new Lenis({duration:1.1,anchors:true,prevent:node=>!!node.closest('.modal-backdrop,.mobile-menu')});lenis.on('scroll',ScrollTrigger.update);tick=(time)=>lenis?.raf(time*1000);gsap.ticker.add(tick);gsap.ticker.lagSmoothing(0);
let disposeMotion=()=>{};
const ctx=gsap.context(()=>{
if(root.current)disposeMotion=cinematicMotion(gsap,ScrollTrigger,root.current);
 
 gsap.to('.hero-visual',{yPercent:12,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});
 gsap.to('.hero-stay',{xPercent:-14,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});

 
 gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.fromTo(el,{y:30,opacity:0},{y:0,opacity:1,duration:.8,scrollTrigger:{trigger:el,start:'top 92%'}}));
 gsap.fromTo('.manifesto-word',{color:'#868075'},{color:'#171715',stagger:.15,ease:'none',scrollTrigger:{trigger:'.manifesto',start:'top 70%',end:'bottom 65%',scrub:1}});
 const age=gsap.timeline({scrollTrigger:{trigger:'.changes',start:'top top',end:'+=100%',pin:(document.querySelector('.changes')?.getBoundingClientRect().height??Infinity)<=window.innerHeight+5,scrub:1}});
 age.to('.time-portrait',{scale:1.04},0).to('.time-meter i',{scaleX:1},0);
 ScrollTrigger.create({trigger:'.science',start:'top top',end:'+=100%',pin:(document.querySelector('.science')?.getBoundingClientRect().height??Infinity)<=window.innerHeight+5,scrub:1,onUpdate:self=>setLayer(Math.min(2,Math.floor(self.progress*3)))});

 gsap.fromTo('.foot-word',{yPercent:20},{yPercent:-5,ease:'none',scrollTrigger:{trigger:'.cta',start:'top bottom',end:'bottom bottom',scrub:1}});
},root);return()=>{disposeMotion();ctx.revert();if(tick)gsap.ticker.remove(tick);lenis?.destroy()}});
dispose=()=>mm.revert()};void initialize();return()=>{cancelled=true;dispose()}},[loading]);
useEffect(()=>{const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)setNavLight(['hero','changes','results','cta'].some(c=>entry.target.classList.contains(c)))})},{rootMargin:'-1px 0px -94% 0px',threshold:0});document.querySelectorAll('main section').forEach(section=>observer.observe(section));return()=>observer.disconnect()},[]);
useEffect(()=>{if(!quiz&&!policy&&!menu)return;const prev=document.activeElement as HTMLElement;const dialog=document.querySelector<HTMLElement>('.quiz-dialog,.mobile-menu');dialog?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setQuiz(false);setPolicy(null);setMenu(false)}if(e.key==='Tab'){const nodes=dialog?.querySelectorAll<HTMLElement>('button,a,input');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=old;prev?.focus()}},[quiz,policy,menu]);
function startQuiz(){setStep(0);setAnswers([]);setSaved(false);setQuiz(true)}
const result=answers[2]==='Often irritated'||answers[1]==='Sensitive'?'Comfort first':answers[0]==='Uneven-looking tone'?'A thoughtful tone routine':answers[0]==='Fine lines'?'Hydration, with consistency':'Your hydration starting point';
const sensitive=answers[2]==='Often irritated'||answers[2]==='Sometimes irritated'||answers[1]==='Sensitive';
const recommended=answers[3]==='A salon consultation'||sensitive?null:answers[3]==='A simple daily ritual'?0:1;
function downloadSummary(){const text=['STILL — skincare concept',result,...answers.map((a,i)=>questions[i].q+' '+a),'Suggested starting point: '+(recommended===null?'Discuss your routine with a skin professional before choosing products.':products[recommended].name+' — '+products[recommended].copy),'This demo is educational. Products and specifications are illustrative; nothing is available for purchase.'].join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='STILL-consultation-summary.txt';a.click();URL.revokeObjectURL(url);setSaved(true)}
return <div ref={root}>
{loading&&<div className="loader" aria-label="Preparing your skin journey"><span className="loader-mark">STILL<span>.</span></span><div className="loader-rule"><i/></div><p>TAKE A MOMENT.</p></div>}
<a inert={quiz||menu||!!policy} className="skip-link" href="#story">Skip to content</a><header inert={quiz||!!policy} className={menu?'menu-open':navLight?'nav-light':'nav-dark'}><a href="#home" className="logo" aria-label="STILL· home">STILL<span>·</span></a><nav aria-label="Main navigation"><a href="#story">Our point of view</a><a href="#science">Beneath the surface</a><a href="#ritual">The collection</a></nav><div className="nav-right"><button className="nav-consult" onClick={startQuiz}>Take the 1-minute skin quiz <Plus size={14}/></button><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></header>
{menu&&<nav className="mobile-menu" aria-label="Mobile navigation" tabIndex={-1}>{[['Our point of view','#story'],['Beneath the surface','#science'],['The collection','#ritual'],['Take the 1-minute skin quiz','#consultation']].map(([label,href])=><a key={href} href={href} onClick={e=>{setMenu(false);if(href==='#consultation'){e.preventDefault();startQuiz()}}}>{label}<Plus size={25}/></a>)}</nav>}
<div className="journey-progress" aria-hidden="true"/><main inert={quiz||menu||!!policy}>
<section className="hero" id="home">
 <div className="hero-visual"><Image src="/images/skin-hero.webp" alt="Extreme close-up of natural skin and a luminous serum bead" fill priority sizes="100vw"/></div>
 <div className="hero-vignette"/><div className="hero-glint" aria-hidden="true"/>
 <p className="hero-intro eyebrow">HYDRATION, MADE PERSONAL.<br/>AN INDEPENDENT BRAND CONCEPT.</p>
 <h1 className="hero-type"><span className="hero-stay">STAY</span><em className="hero-you">you.</em></h1>
 <div className="hero-lower"><p>Hydration for dry, tight skin.<br/>A simpler daily routine.</p><button className="hero-quiz" onClick={startQuiz}><span>Take the skin quiz</span><i><Plus size={25}/></i></button></div>
 <div className="hero-bottom"><a href="#ritual">EXPLORE THE COLLECTION <span className="scroll-line"/></a><span>SKINCARE CONCEPT</span></div>
</section>
<section className="manifesto section" id="story">
 <div className="section-kicker"><p className="eyebrow">01 / A DIFFERENT POINT OF VIEW</p><span>SKIN IS PERSONAL.</span></div>
 <h2 className="manifesto-text" aria-label="Not younger. Not different. Just beautifully, unmistakably you.">{'Not younger. Not different. Just beautifully, unmistakably'.split(' ').map((word,i)=><span className="manifesto-word" key={i}>{word} </span>)}<em className="manifesto-word">you.</em></h2>
 <div className="manifesto-bottom"><span className="vertical-rule"/><p>Every late night. Every sunny afternoon.<br/>Every year of being you.</p><p>Skin changes. Our approach starts with understanding yours, then finding a ritual that belongs in your life.</p><a className="round-link" href="#science" aria-label="Explore beneath the surface"><Plus size={22}/></a></div>
</section>
<section className="changes" aria-label="The changing story of skin">
 <div className="time-portrait"><Image src="/images/skin.webp" fill sizes="100vw" alt="Natural skin portrait"/></div><div className="time-shade"/><div className="time-scan" aria-hidden="true"/>
 <div className="time-top"><p className="eyebrow">02 / SKIN, AS IT IS</p><span>YOUR SKIN HAS BEEN THERE.</span></div>
 <div className="time-copy"><h2>Listen to<br/><em>your skin.</em></h2><p>A routine built around how your skin feels today.</p></div>
 <div className="time-bottom"><p className="small">Natural skin study.<br/>No before-and-after claims.</p></div>
</section>
<section className="science section" id="science">
 <div className="section-kicker"><p className="eyebrow">03 / BENEATH THE SURFACE</p><span>CARE BEGINS WITH UNDERSTANDING.</span></div>
 <div className="science-grid"><div className="science-art"><h2>A little<br/><em>deeper.</em></h2><div className="skin-diagram" aria-label="Simplified skin cross-section"><div className={'skin-layer surface '+(layer===0?'selected':'')}><span>Surface</span></div><div className={'skin-layer epidermis '+(layer===1?'selected':'')}><span>Epidermis</span></div><div className={'skin-layer dermis '+(layer===2?'selected':'')}><span>Dermis</span></div></div><p className="diagram-caption">SKIN CROSS-SECTION / SIMPLIFIED</p></div>
 <div className="layer-detail"><div className="layer-tabs" role="group" aria-label="Skin layers">{['Surface','Epidermis','Dermis'].map((l,i)=><button aria-pressed={layer===i} key={l} onClick={()=>setLayer(i)} className={layer===i?'active':''}>{l}</button>)}</div><div className="layer-copy" key={layer}><p className="eyebrow">{['THE FIRST LINE','THE PROTECTIVE LAYER','THE SUPPORT STRUCTURE'][layer]}</p><h3>{['Comfort starts here.','Respect the barrier.','Know the foundations.'][layer]}</h3><p>{['The outer surface helps keep moisture in. Humectants such as glycerin and hyaluronic acid are used in skincare to support hydration.','The epidermis is your outer protective layer. Ceramides are used in moisturisers designed to support its moisture barrier.','The dermis contains connective tissue, blood vessels and other structures. A topical ritual is not a promise to rebuild this layer.'][layer]}</p><div className="ingredient"><span>{['HYDRATION FOCUS','BARRIER FOCUS','PROFESSIONAL GUIDANCE'][layer]}</span><strong>{['Glycerin + hyaluronic acid','Ceramides + gentle care','An individual consultation'][layer]}</strong></div></div><p className="small">Ingredient education, not a product penetration claim.<br/>Ask your professional about suitability.</p></div></div>
</section>
 <section className="ingredient-journey" aria-label="Inside the formula">
 {[['HYALURONIC','HYDRATION','A humectant used in skincare to help the surface retain moisture.'],['GLYCERIN','COMFORT','A familiar moisturising ingredient for skin that feels dry or tight.'],['PANTHENOL','GENTLE CARE','An ingredient used in soothing and moisturising skincare formulas.']].map((item,i)=><article className="ingredient-scene" key={item[0]}><span className="ingredient-ghost">{item[0]}</span><div className="ingredient-scene-copy"><h2>{item[0]}</h2><strong>{item[1]} <span>↑</span></strong><p>{item[2]}</p></div><div className="ingredient-product ingredient-art" data-kind={['gel','liquid','cream'][i]}><div className="ingredient-product-media"><Image src={['/images/hyaluronic-gel.webp','/images/glycerin-liquid.webp','/images/panthenol-cream.webp'][i]} fill sizes="(max-width:760px) 88vw, 42vw" alt={['Translucent hydrogel ribbon with delicate bubbles','Viscous liquid forming concentric ripples','Sculptural fold of moisturising cream'][i]}/></div><span className="ingredient-product-label">{['HYDRATING GEL','LIQUID TEXTURE','CREAM TEXTURE'][i]}</span></div><div className="ingredient-orb" aria-hidden="true"><i/><i/><i/></div></article>)}
 </section>
<section className="treatment section" id="ritual">
 <div className="section-kicker"><p className="eyebrow">04 / THE COLLECTION</p><span>LESS NOISE. MORE RITUAL.</span></div>
 <div className="orbit-layout"><div className="orbit-stage" role="group" aria-label="Product carousel" tabIndex={0} onKeyDown={e=>{if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();setActive(v=>1-v)}}} data-active={active} onDragStart={e=>e.preventDefault()}
 onPointerDown={e=>{dragged.current=false;dragStart.current={x:e.clientX,y:e.clientY}}}
 onPointerUp={e=>{if(dragStart.current){const dx=e.clientX-dragStart.current.x,dy=e.clientY-dragStart.current.y;if(Math.abs(dx)>45&&Math.abs(dy)<60){setActive(active===0?1:0);dragged.current=true}dragStart.current=null}}}
 onPointerCancel={()=>{dragStart.current=null;dragged.current=false}} onClickCapture={e=>{if(dragged.current){e.preventDefault();e.stopPropagation();dragged.current=false}}}>
 <span className="orbit-word" aria-hidden="true">{products[active].focus}</span><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/>
 {products.map((p,i)=><button key={p.name} className={'vessel vessel-'+i+(active===i?' selected':'')} onClick={()=>setActive(i)} aria-label={`Select ${p.name}`} aria-pressed={active===i}><Image draggable={false} src={p.image} alt={p.name+' concept packaging'} fill sizes="(max-width:760px) 65vw, 35vw"/><span className="vessel-ingredients">{p.ingredients.join(" · ")}</span></button>)}
 <span className="orbit-caption">DRAG TO DISCOVER / OR USE THE CONTROLS</span>
 </div>
 <div className="treatment-copy"><p className="eyebrow">{products[active].sub}</p><div className="product-copy" key={active}><h2>{active===0?<>A daily<br/><em>reset.</em></>:<>A slow<br/><em>moment.</em></>}</h2><h3>{products[active].name}</h3><p>{products[active].copy}</p><p className="product-size">{products[active].size}</p><p className="product-use"><strong>How it fits:</strong> {products[active].use}</p><details className="ingredient-details"><summary>Inside the ritual <Plus size={18}/></summary><p>{products[active].ingredients.join(' · ')}</p><span className="small">Featured ingredients for this concept, not a full INCI list.</span></details></div>
 <div className="product-controls"><button onClick={()=>setActive(active===0?1:0)} aria-label="Previous ritual"><ChevronLeft size={22}/></button><span aria-live="polite">{products[active].name}</span><button onClick={()=>setActive(active===0?1:0)} aria-label="Next ritual"><ChevronRight size={22}/></button></div>
 <button className="text-link" onClick={startQuiz}>Take the 1-minute skin quiz <Plus size={18}/></button></div>
 </div><p className="collection-footnote">Independent skincare concept. Sample packaging and specifications; not available for purchase.</p>
</section>
<section className="results section" id="results"><div className="results-heading"><p className="eyebrow">05 / A CLOSER LOOK</p><h2>Look closer.<br/><em>Stay honest.</em></h2><p>Your skin story is personal.<br/>A considered routine starts with listening.</p></div><div className="reflections" role="group" aria-label="Care notes" tabIndex={0} onKeyDown={e=>{if(e.key==="ArrowRight"||e.key==="ArrowLeft"){e.preventDefault();setReview(v=>(v+(e.key==="ArrowRight"?1:2))%3)}}}><p className="eyebrow">CARE NOTES</p><h3>{reflections[review].title}</h3><p>{reflections[review].copy}</p><div className="dots">{reflections.map((r,i)=><button key={i} aria-label={`Care note ${i+1}`} aria-pressed={review===i} className={review===i?'active':''} onClick={()=>setReview(i)}/>)}</div><span className="small">Editorial guidance from the concept, not a customer testimonial.</span></div></section>
<section className="quiz-section section"><p className="eyebrow">FOUR QUESTIONS. A THOUGHTFUL START.</p><h2>Your skin.<br/><em>Your starting point.</em></h2><button className="pill dark" onClick={startQuiz}>Take the 1-minute skin quiz <Plus size={16}/></button><p className="small">About a minute. No email required.</p></section>
<section className="trust section"><h2>Clear about<br/><em>what’s inside.</em></h2><div className="trust-grid"><p><strong>Ingredients you can follow.</strong> Each product has one consistent list of featured ingredients. Full formula, sourcing and testing details belong on real product labels.</p><p><strong>Transparent concept scope.</strong> This independent concept has no clinical trials, customer reviews or salon partnerships to claim. It shows an approach to the brand and routine.</p><p><strong>A conversation, not a diagnosis.</strong> The quiz gives a discussion summary. A professional can help you decide what is appropriate for your skin.</p></div></section><section className="faq section"><p className="eyebrow">A FEW THINGS, ANSWERED</p>{[['Can I buy these products?','STILL is an independent skincare brand concept by Copywrk. The products, sizes and routines are sample content. There is no checkout, price list or salon network. Contact Copywrk to discuss the website concept.'],['What happens after the quiz?','You get a suggested starting point, your answers and a downloadable text summary. You can explore the matching concept product or bring the summary to your own skin professional.'],['Is this a replacement for a dermatologist?','No. These rituals and the quiz are general skincare education. Persistent irritation, acne or changing skin lesions should be discussed with a dermatologist.'],['How do I choose a treatment?','Start with a consultation. Share your concerns, current routine, sensitivities and any recent treatments so your professional can assess suitability.'],['Will everyone see the same results?','No. Skin response varies. Discuss realistic expectations, the products used and aftercare with your professional.']].map(([q,a],i)=><div className="faq-item" key={q}><button id={`faq-question-${i}`} aria-controls={`faq-answer-${i}`} aria-expanded={openFaq===i} onClick={()=>setOpenFaq(openFaq===i?null:i)}>{q}{openFaq===i?<Minus size={18}/>:<Plus size={18}/>}</button><p id={`faq-answer-${i}`} role="region" aria-labelledby={`faq-question-${i}`} hidden={openFaq!==i}>{a}</p></div>)}</section>
<section className="cta section" id="consultation"><span className="foot-word" aria-hidden="true">STILL.</span><p className="eyebrow">06 / THE NEXT CHAPTER IS YOURS</p><h2>The next chapter.<br/><em>Yours.</em></h2><div className="cta-grid"><p>This is a skincare brand concept by Copywrk.<br/>Explore your routine or ask about a website for your own brand.</p><div className="contact-options"><a className="pill light" href="mailto:copywrk0@gmail.com?subject=STILL%20website%20concept">Email Copywrk about this concept <Plus size={18}/></a><button className="text-link" onClick={startQuiz}>Get a skin quiz summary <Plus size={18}/></button>{wa&&<a className="text-link" href={wa} target="_blank" rel="noreferrer">Send a WhatsApp enquiry <MessageCircle size={16}/></a>}</div></div></section>
</main><footer inert={quiz||menu||!!policy}><a href="#home" className="logo">STILL<span>·</span></a><p>Thoughtful hydration. A routine that feels like yours.</p><span>© {new Date().getFullYear()} STILL · Independent skincare concept by Copywrk.</span><div className="footer-links"><a href="mailto:copywrk0@gmail.com">Contact Copywrk</a><a href="https://copywrk.website" target="_blank" rel="noreferrer">Copywrk website</a><button onClick={()=>setPolicy('privacy')}>Privacy</button><button onClick={()=>setPolicy('terms')}>Terms</button><a href="#home">Back to top</a></div></footer>
{policy&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setPolicy(null)}}><div className="quiz-dialog" role="dialog" aria-modal="true" aria-labelledby="policy-title" tabIndex={-1}><button className="quiz-close" aria-label="Close policy" onClick={()=>setPolicy(null)}><X/></button><h2 id="policy-title">{policy==='privacy'?'Your privacy':'Concept terms'}</h2>{policy==='privacy'?<><p>Your quiz answers stay in this page’s temporary memory. They are not sent to a server or stored after reloading. This project does not install analytics or marketing cookies.</p><p>Downloading a summary creates a text file on your device. If you choose an email or WhatsApp link, that service receives the information you send under its own privacy policy.</p><p>Hosting providers may process ordinary request logs. Questions about this concept: <a href="mailto:copywrk0@gmail.com">copywrk0@gmail.com</a>.</p></>:<><p>STILL is an independent portfolio concept by Copywrk. Products, packaging and sizes are illustrative. Nothing is offered for sale, and no salon, dermatologist or customer endorsement is implied.</p><p>The quiz and editorial content provide general discussion prompts. They do not diagnose skin conditions or recommend a personal treatment. No results are promised.</p><p>For enquiries about the website design: <a href="mailto:copywrk0@gmail.com">copywrk0@gmail.com</a>.</p></>}</div></div>}
{quiz&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setQuiz(false)}}><div className="quiz-dialog" role="dialog" aria-modal="true" aria-labelledby="quiz-title" tabIndex={-1}><button className="quiz-close" aria-label="Close quiz" onClick={()=>setQuiz(false)}><X/></button><span className="logo">STILL.</span>{step<4?<><p className="eyebrow">YOUR SKIN, UNDERSTOOD / 0{step+1} OF 04</p><div className="quiz-progress"><i style={{width:`${(step+1)*25}%`}}/></div><h2 id="quiz-title">{questions[step].q}</h2><div className="answers">{questions[step].opts.map(a=><button key={a} onClick={()=>{setAnswers([...answers.slice(0,step),a]);setStep(step+1)}}>{a}<Plus size={15}/></button>)}</div>{step>0&&<button className="quiz-back" onClick={()=>setStep(step-1)}>Previous question</button>}</>:<><p className="eyebrow">YOUR CONVERSATION STARTER</p><h2 id="quiz-title">{result}</h2><p>{result==='Comfort first'?'Start gently. Discuss your sensitivity with a professional before trying active ingredients or a salon treatment.':'Discuss a gentle hydration and barrier-support routine, daily sun protection and whether a salon ritual suits your skin.'}</p><ul>{answers.map((a,i)=><li key={i}><Check size={16}/>{a}</li>)}</ul><p className="small">A suggested discussion topic, not a diagnosis or personalised treatment prescription.</p><div className="quiz-result"><h3>{recommended===null?'Start with professional guidance':products[recommended].name}</h3><p>{recommended===null?'Pause new products and discuss your current routine, reactions and preferences with a professional.':products[recommended].copy+' '+products[recommended].use}</p><p className="small">Concept product suggestion. No purchase or booking is made.</p></div><button className="pill dark" onClick={downloadSummary}>Download my consultation summary <Plus size={16}/></button>{saved&&<p role="status">Your text summary is ready to keep or share.</p>}{recommended!==null&&<a className="text-link" href="#ritual" onClick={()=>{setActive(recommended);setQuiz(false)}}>Explore {products[recommended].name} <Plus size={16}/></a>}{wa&&<a className="text-link" href={`${wa.split('?')[0]}?text=${encodeURIComponent('Hello, my STILL concept quiz summary: '+answers.join('; '))}`} target="_blank" rel="noreferrer">Send summary on WhatsApp <MessageCircle size={16}/></a>}<button className="quiz-back" onClick={startQuiz}>Start again</button></>}</div></div>}
</div>}
